version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: outbox
      POSTGRES_PASSWORD: outbox
      POSTGRES_DB: outbox
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./deployments/docker/postgresql/init.sql:/docker-entrypoint-initdb.d/init.sql

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--jetstream"

  app1:
    build: .
    environment:
      INSTANCE_ID: "1"
      DATABASE_URL: "postgres://outbox:outbox@postgres:5432/outbox?sslmode=disable"
      DATABASE_MAX_CONNECTIONS: "10"
      NATS_URL: "nats://nats:4222"
      WORKER_POLL_INTERVAL: "1s"
      WORKER_BATCH_SIZE: "100"
      WORKER_MAX_RETRIES: "3"
    depends_on:
      - postgres
      - nats

  app2:
    build: .
    environment:
      INSTANCE_ID: "1"
      DATABASE_URL: "postgres://outbox:outbox@postgres:5432/outbox?sslmode=disable"
      DATABASE_MAX_CONNECTIONS: "10"
      NATS_URL: "nats://nats:4222"
      WORKER_POLL_INTERVAL: "1s"
      WORKER_BATCH_SIZE: "100"
      WORKER_MAX_RETRIES: "3"
    depends_on:
      - postgres
      - nats

volumes:
  postgres_data: 